name: Security Scan

on:
  schedule: 
     - cron: '*/30 * * * *'

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
    - name: Run Dastardly Action Step
      uses: PortSwigger/dastardly-github-action@main
      with:
        target-url: 'https://devcoiapiapp.azurewebsites.net/api/Task/selfSubmit'
